/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "dbus-interface.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  guint use_gvariant : 1;
  guint emits_changed_signal : 1;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface net.sapples.LiveCaptions.External
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:DBLCapExternal
 * @title: DBLCapExternal
 * @short_description: Generated C code for the net.sapples.LiveCaptions.External D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-net-sapples-LiveCaptions-External.top_of_page">net.sapples.LiveCaptions.External</link> D-Bus interface in C.
 */

/* ---- Introspection data for net.sapples.LiveCaptions.External ---- */

static const _ExtendedGDBusMethodInfo _dblcap_external_method_info_allow_keep_above =
{
  {
    -1,
    (gchar *) "AllowKeepAbove",
    NULL,
    NULL,
    NULL
  },
  "handle-allow-keep-above",
  FALSE
};

static const GDBusMethodInfo * const _dblcap_external_method_info_pointers[] =
{
  &_dblcap_external_method_info_allow_keep_above.parent_struct,
  NULL
};

static const _ExtendedGDBusPropertyInfo _dblcap_external_property_info_keep_above =
{
  {
    -1,
    (gchar *) "KeepAbove",
    (gchar *) "b",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "keep-above",
  FALSE,
  TRUE
};

static const GDBusPropertyInfo * const _dblcap_external_property_info_pointers[] =
{
  &_dblcap_external_property_info_keep_above.parent_struct,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _dblcap_external_interface_info =
{
  {
    -1,
    (gchar *) "net.sapples.LiveCaptions.External",
    (GDBusMethodInfo **) &_dblcap_external_method_info_pointers,
    NULL,
    (GDBusPropertyInfo **) &_dblcap_external_property_info_pointers,
    NULL
  },
  "external",
};


/**
 * dblcap_external_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-net-sapples-LiveCaptions-External.top_of_page">net.sapples.LiveCaptions.External</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
dblcap_external_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_dblcap_external_interface_info.parent_struct;
}

/**
 * dblcap_external_override_properties:
 * @klass: The class structure for a #GObject derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #DBLCapExternal interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
dblcap_external_override_properties (GObjectClass *klass, guint property_id_begin)
{
  g_object_class_override_property (klass, property_id_begin++, "keep-above");
  return property_id_begin - 1;
}



/**
 * DBLCapExternal:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-net-sapples-LiveCaptions-External.top_of_page">net.sapples.LiveCaptions.External</link>.
 */

/**
 * DBLCapExternalIface:
 * @parent_iface: The parent interface.
 * @handle_allow_keep_above: Handler for the #DBLCapExternal::handle-allow-keep-above signal.
 * @get_keep_above: Getter for the #DBLCapExternal:keep-above property.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-net-sapples-LiveCaptions-External.top_of_page">net.sapples.LiveCaptions.External</link>.
 */

typedef DBLCapExternalIface DBLCapExternalInterface;
G_DEFINE_INTERFACE (DBLCapExternal, dblcap_external, G_TYPE_OBJECT)

static void
dblcap_external_default_init (DBLCapExternalIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * DBLCapExternal::handle-allow-keep-above:
   * @object: A #DBLCapExternal.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-net-sapples-LiveCaptions-External.AllowKeepAbove">AllowKeepAbove()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call dblcap_external_complete_allow_keep_above() or e.g. g_dbus_method_invocation_return_error() on it) and no other signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %G_DBUS_METHOD_INVOCATION_HANDLED or %TRUE if the invocation was handled, %G_DBUS_METHOD_INVOCATION_UNHANDLED or %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-allow-keep-above",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (DBLCapExternalIface, handle_allow_keep_above),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /* GObject properties for D-Bus properties: */
  /**
   * DBLCapExternal:keep-above:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-net-sapples-LiveCaptions-External.KeepAbove">"KeepAbove"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boolean ("keep-above", "KeepAbove", "KeepAbove", FALSE, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
}

/**
 * dblcap_external_get_keep_above: (skip)
 * @object: A #DBLCapExternal.
 *
 * Gets the value of the <link linkend="gdbus-property-net-sapples-LiveCaptions-External.KeepAbove">"KeepAbove"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gboolean 
dblcap_external_get_keep_above (DBLCapExternal *object)
{
  return DBLCAP_EXTERNAL_GET_IFACE (object)->get_keep_above (object);
}

/**
 * dblcap_external_set_keep_above: (skip)
 * @object: A #DBLCapExternal.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-net-sapples-LiveCaptions-External.KeepAbove">"KeepAbove"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
dblcap_external_set_keep_above (DBLCapExternal *object, gboolean value)
{
  g_object_set (G_OBJECT (object), "keep-above", value, NULL);
}

/**
 * dblcap_external_call_allow_keep_above:
 * @proxy: A #DBLCapExternalProxy.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-net-sapples-LiveCaptions-External.AllowKeepAbove">AllowKeepAbove()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call dblcap_external_call_allow_keep_above_finish() to get the result of the operation.
 *
 * See dblcap_external_call_allow_keep_above_sync() for the synchronous, blocking version of this method.
 */
void
dblcap_external_call_allow_keep_above (
    DBLCapExternal *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "AllowKeepAbove",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * dblcap_external_call_allow_keep_above_finish:
 * @proxy: A #DBLCapExternalProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to dblcap_external_call_allow_keep_above().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with dblcap_external_call_allow_keep_above().
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
dblcap_external_call_allow_keep_above_finish (
    DBLCapExternal *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * dblcap_external_call_allow_keep_above_sync:
 * @proxy: A #DBLCapExternalProxy.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-net-sapples-LiveCaptions-External.AllowKeepAbove">AllowKeepAbove()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See dblcap_external_call_allow_keep_above() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
dblcap_external_call_allow_keep_above_sync (
    DBLCapExternal *proxy,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "AllowKeepAbove",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * dblcap_external_complete_allow_keep_above:
 * @object: A #DBLCapExternal.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-net-sapples-LiveCaptions-External.AllowKeepAbove">AllowKeepAbove()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
dblcap_external_complete_allow_keep_above (
    DBLCapExternal *object G_GNUC_UNUSED,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * DBLCapExternalProxy:
 *
 * The #DBLCapExternalProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * DBLCapExternalProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #DBLCapExternalProxy.
 */

struct _DBLCapExternalProxyPrivate
{
  GData *qdata;
};

static void dblcap_external_proxy_iface_init (DBLCapExternalIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (DBLCapExternalProxy, dblcap_external_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (DBLCapExternalProxy)
                         G_IMPLEMENT_INTERFACE (DBLCAP_TYPE_EXTERNAL, dblcap_external_proxy_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (DBLCapExternalProxy, dblcap_external_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (DBLCAP_TYPE_EXTERNAL, dblcap_external_proxy_iface_init))

#endif
static void
dblcap_external_proxy_finalize (GObject *object)
{
  DBLCapExternalProxy *proxy = DBLCAP_EXTERNAL_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (dblcap_external_proxy_parent_class)->finalize (object);
}

static void
dblcap_external_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  info = (const _ExtendedGDBusPropertyInfo *) _dblcap_external_property_info_pointers[prop_id - 1];
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (object), info->parent_struct.name);
  if (info->use_gvariant)
    {
      g_value_set_variant (value, variant);
    }
  else
    {
      if (variant != NULL)
        g_dbus_gvariant_to_gvalue (variant, value);
    }
  if (variant != NULL)
    g_variant_unref (variant);
}

static void
dblcap_external_proxy_set_property_cb (GDBusProxy *proxy,
  GAsyncResult *res,
  gpointer      user_data)
{
  const _ExtendedGDBusPropertyInfo *info = user_data;
  GError *error;
  GVariant *_ret;
  error = NULL;
  _ret = g_dbus_proxy_call_finish (proxy, res, &error);
  if (!_ret)
    {
      g_warning ("Error setting property '%s' on interface net.sapples.LiveCaptions.External: %s (%s, %d)",
                 info->parent_struct.name, 
                 error->message, g_quark_to_string (error->domain), error->code);
      g_error_free (error);
    }
  else
    {
      g_variant_unref (_ret);
    }
}

static void
dblcap_external_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  info = (const _ExtendedGDBusPropertyInfo *) _dblcap_external_property_info_pointers[prop_id - 1];
  variant = g_dbus_gvalue_to_gvariant (value, G_VARIANT_TYPE (info->parent_struct.signature));
  g_dbus_proxy_call (G_DBUS_PROXY (object),
    "org.freedesktop.DBus.Properties.Set",
    g_variant_new ("(ssv)", "net.sapples.LiveCaptions.External", info->parent_struct.name, variant),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    NULL, (GAsyncReadyCallback) dblcap_external_proxy_set_property_cb, (GDBusPropertyInfo *) &info->parent_struct);
  g_variant_unref (variant);
}

static void
dblcap_external_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  gsize n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_dblcap_external_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], DBLCAP_TYPE_EXTERNAL);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, DBLCAP_TYPE_EXTERNAL);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
dblcap_external_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  DBLCapExternalProxy *proxy = DBLCAP_EXTERNAL_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_dblcap_external_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_dblcap_external_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static gboolean 
dblcap_external_proxy_get_keep_above (DBLCapExternal *object)
{
  DBLCapExternalProxy *proxy = DBLCAP_EXTERNAL_PROXY (object);
  GVariant *variant;
  gboolean value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "KeepAbove");
  if (variant != NULL)
    {
      value = g_variant_get_boolean (variant);
      g_variant_unref (variant);
    }
  return value;
}

static void
dblcap_external_proxy_init (DBLCapExternalProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = dblcap_external_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, DBLCAP_TYPE_EXTERNAL_PROXY, DBLCapExternalProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), dblcap_external_interface_info ());
}

static void
dblcap_external_proxy_class_init (DBLCapExternalProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = dblcap_external_proxy_finalize;
  gobject_class->get_property = dblcap_external_proxy_get_property;
  gobject_class->set_property = dblcap_external_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = dblcap_external_proxy_g_signal;
  proxy_class->g_properties_changed = dblcap_external_proxy_g_properties_changed;

  dblcap_external_override_properties (gobject_class, 1);

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (DBLCapExternalProxyPrivate));
#endif
}

static void
dblcap_external_proxy_iface_init (DBLCapExternalIface *iface)
{
  iface->get_keep_above = dblcap_external_proxy_get_keep_above;
}

/**
 * dblcap_external_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-net-sapples-LiveCaptions-External.top_of_page">net.sapples.LiveCaptions.External</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call dblcap_external_proxy_new_finish() to get the result of the operation.
 *
 * See dblcap_external_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
dblcap_external_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (DBLCAP_TYPE_EXTERNAL_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "net.sapples.LiveCaptions.External", NULL);
}

/**
 * dblcap_external_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to dblcap_external_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with dblcap_external_proxy_new().
 *
 * Returns: (transfer full) (type DBLCapExternalProxy): The constructed proxy object or %NULL if @error is set.
 */
DBLCapExternal *
dblcap_external_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return DBLCAP_EXTERNAL (ret);
  else
    return NULL;
}

/**
 * dblcap_external_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-net-sapples-LiveCaptions-External.top_of_page">net.sapples.LiveCaptions.External</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See dblcap_external_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type DBLCapExternalProxy): The constructed proxy object or %NULL if @error is set.
 */
DBLCapExternal *
dblcap_external_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (DBLCAP_TYPE_EXTERNAL_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "net.sapples.LiveCaptions.External", NULL);
  if (ret != NULL)
    return DBLCAP_EXTERNAL (ret);
  else
    return NULL;
}


/**
 * dblcap_external_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like dblcap_external_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call dblcap_external_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See dblcap_external_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
dblcap_external_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (DBLCAP_TYPE_EXTERNAL_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "net.sapples.LiveCaptions.External", NULL);
}

/**
 * dblcap_external_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to dblcap_external_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with dblcap_external_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type DBLCapExternalProxy): The constructed proxy object or %NULL if @error is set.
 */
DBLCapExternal *
dblcap_external_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return DBLCAP_EXTERNAL (ret);
  else
    return NULL;
}

/**
 * dblcap_external_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like dblcap_external_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See dblcap_external_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type DBLCapExternalProxy): The constructed proxy object or %NULL if @error is set.
 */
DBLCapExternal *
dblcap_external_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (DBLCAP_TYPE_EXTERNAL_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "net.sapples.LiveCaptions.External", NULL);
  if (ret != NULL)
    return DBLCAP_EXTERNAL (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * DBLCapExternalSkeleton:
 *
 * The #DBLCapExternalSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * DBLCapExternalSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #DBLCapExternalSkeleton.
 */

struct _DBLCapExternalSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_dblcap_external_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  DBLCapExternalSkeleton *skeleton = DBLCAP_EXTERNAL_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  guint num_extra;
  gsize n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], DBLCAP_TYPE_EXTERNAL);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, DBLCAP_TYPE_EXTERNAL);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_dblcap_external_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  DBLCapExternalSkeleton *skeleton = DBLCAP_EXTERNAL_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_dblcap_external_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_dblcap_external_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  DBLCapExternalSkeleton *skeleton = DBLCAP_EXTERNAL_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_dblcap_external_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _dblcap_external_skeleton_vtable =
{
  _dblcap_external_skeleton_handle_method_call,
  _dblcap_external_skeleton_handle_get_property,
  _dblcap_external_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
dblcap_external_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return dblcap_external_interface_info ();
}

static GDBusInterfaceVTable *
dblcap_external_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_dblcap_external_skeleton_vtable;
}

static GVariant *
dblcap_external_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  DBLCapExternalSkeleton *skeleton = DBLCAP_EXTERNAL_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_dblcap_external_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _dblcap_external_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _dblcap_external_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _dblcap_external_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "net.sapples.LiveCaptions.External", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static gboolean _dblcap_external_emit_changed (gpointer user_data);

static void
dblcap_external_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
  DBLCapExternalSkeleton *skeleton = DBLCAP_EXTERNAL_SKELETON (_skeleton);
  gboolean emit_changed = FALSE;

  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    {
      g_source_destroy (skeleton->priv->changed_properties_idle_source);
      skeleton->priv->changed_properties_idle_source = NULL;
      emit_changed = TRUE;
    }
  g_mutex_unlock (&skeleton->priv->lock);

  if (emit_changed)
    _dblcap_external_emit_changed (skeleton);
}

static void dblcap_external_skeleton_iface_init (DBLCapExternalIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (DBLCapExternalSkeleton, dblcap_external_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (DBLCapExternalSkeleton)
                         G_IMPLEMENT_INTERFACE (DBLCAP_TYPE_EXTERNAL, dblcap_external_skeleton_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (DBLCapExternalSkeleton, dblcap_external_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (DBLCAP_TYPE_EXTERNAL, dblcap_external_skeleton_iface_init))

#endif
static void
dblcap_external_skeleton_finalize (GObject *object)
{
  DBLCapExternalSkeleton *skeleton = DBLCAP_EXTERNAL_SKELETON (object);
  guint n;
  for (n = 0; n < 1; n++)
    g_value_unset (&skeleton->priv->properties[n]);
  g_free (skeleton->priv->properties);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (dblcap_external_skeleton_parent_class)->finalize (object);
}

static void
dblcap_external_skeleton_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  DBLCapExternalSkeleton *skeleton = DBLCAP_EXTERNAL_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  g_mutex_lock (&skeleton->priv->lock);
  g_value_copy (&skeleton->priv->properties[prop_id - 1], value);
  g_mutex_unlock (&skeleton->priv->lock);
}

static gboolean
_dblcap_external_emit_changed (gpointer user_data)
{
  DBLCapExternalSkeleton *skeleton = DBLCAP_EXTERNAL_SKELETON (user_data);
  GList *l;
  GVariantBuilder builder;
  GVariantBuilder invalidated_builder;
  guint num_changes;

  g_mutex_lock (&skeleton->priv->lock);
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  g_variant_builder_init (&invalidated_builder, G_VARIANT_TYPE ("as"));
  for (l = skeleton->priv->changed_properties, num_changes = 0; l != NULL; l = l->next)
    {
      ChangedProperty *cp = l->data;
      GVariant *variant;
      const GValue *cur_value;

      cur_value = &skeleton->priv->properties[cp->prop_id - 1];
      if (!_g_value_equal (cur_value, &cp->orig_value))
        {
          variant = g_dbus_gvalue_to_gvariant (cur_value, G_VARIANT_TYPE (cp->info->parent_struct.signature));
          g_variant_builder_add (&builder, "{sv}", cp->info->parent_struct.name, variant);
          g_variant_unref (variant);
          num_changes++;
        }
    }
  if (num_changes > 0)
    {
      GList *connections, *ll;
      GVariant *signal_variant;
      signal_variant = g_variant_ref_sink (g_variant_new ("(sa{sv}as)", "net.sapples.LiveCaptions.External",
                                           &builder, &invalidated_builder));
      connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));
      for (ll = connections; ll != NULL; ll = ll->next)
        {
          GDBusConnection *connection = ll->data;

          g_dbus_connection_emit_signal (connection,
                                         NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)),
                                         "org.freedesktop.DBus.Properties",
                                         "PropertiesChanged",
                                         signal_variant,
                                         NULL);
        }
      g_variant_unref (signal_variant);
      g_list_free_full (connections, g_object_unref);
    }
  else
    {
      g_variant_builder_clear (&builder);
      g_variant_builder_clear (&invalidated_builder);
    }
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  skeleton->priv->changed_properties = NULL;
  skeleton->priv->changed_properties_idle_source = NULL;
  g_mutex_unlock (&skeleton->priv->lock);
  return FALSE;
}

static void
_dblcap_external_schedule_emit_changed (DBLCapExternalSkeleton *skeleton, const _ExtendedGDBusPropertyInfo *info, guint prop_id, const GValue *orig_value)
{
  ChangedProperty *cp;
  GList *l;
  cp = NULL;
  for (l = skeleton->priv->changed_properties; l != NULL; l = l->next)
    {
      ChangedProperty *i_cp = l->data;
      if (i_cp->info == info)
        {
          cp = i_cp;
          break;
        }
    }
  if (cp == NULL)
    {
      cp = g_new0 (ChangedProperty, 1);
      cp->prop_id = prop_id;
      cp->info = info;
      skeleton->priv->changed_properties = g_list_prepend (skeleton->priv->changed_properties, cp);
      g_value_init (&cp->orig_value, G_VALUE_TYPE (orig_value));
      g_value_copy (orig_value, &cp->orig_value);
    }
}

static void
dblcap_external_skeleton_notify (GObject      *object,
  GParamSpec *pspec G_GNUC_UNUSED)
{
  DBLCapExternalSkeleton *skeleton = DBLCAP_EXTERNAL_SKELETON (object);
  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties != NULL &&
      skeleton->priv->changed_properties_idle_source == NULL)
    {
      skeleton->priv->changed_properties_idle_source = g_idle_source_new ();
      g_source_set_priority (skeleton->priv->changed_properties_idle_source, G_PRIORITY_DEFAULT);
      g_source_set_callback (skeleton->priv->changed_properties_idle_source, _dblcap_external_emit_changed, g_object_ref (skeleton), (GDestroyNotify) g_object_unref);
      g_source_set_name (skeleton->priv->changed_properties_idle_source, "[generated] _dblcap_external_emit_changed");
      g_source_attach (skeleton->priv->changed_properties_idle_source, skeleton->priv->context);
      g_source_unref (skeleton->priv->changed_properties_idle_source);
    }
  g_mutex_unlock (&skeleton->priv->lock);
}

static void
dblcap_external_skeleton_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  const _ExtendedGDBusPropertyInfo *info;
  DBLCapExternalSkeleton *skeleton = DBLCAP_EXTERNAL_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  info = (const _ExtendedGDBusPropertyInfo *) _dblcap_external_property_info_pointers[prop_id - 1];
  g_mutex_lock (&skeleton->priv->lock);
  g_object_freeze_notify (object);
  if (!_g_value_equal (value, &skeleton->priv->properties[prop_id - 1]))
    {
      if (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)) != NULL &&
          info->emits_changed_signal)
        _dblcap_external_schedule_emit_changed (skeleton, info, prop_id, &skeleton->priv->properties[prop_id - 1]);
      g_value_copy (value, &skeleton->priv->properties[prop_id - 1]);
      g_object_notify_by_pspec (object, pspec);
    }
  g_mutex_unlock (&skeleton->priv->lock);
  g_object_thaw_notify (object);
}

static void
dblcap_external_skeleton_init (DBLCapExternalSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = dblcap_external_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, DBLCAP_TYPE_EXTERNAL_SKELETON, DBLCapExternalSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
  skeleton->priv->properties = g_new0 (GValue, 1);
  g_value_init (&skeleton->priv->properties[0], G_TYPE_BOOLEAN);
}

static gboolean 
dblcap_external_skeleton_get_keep_above (DBLCapExternal *object)
{
  DBLCapExternalSkeleton *skeleton = DBLCAP_EXTERNAL_SKELETON (object);
  gboolean value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_boolean (&(skeleton->priv->properties[0]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static void
dblcap_external_skeleton_class_init (DBLCapExternalSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = dblcap_external_skeleton_finalize;
  gobject_class->get_property = dblcap_external_skeleton_get_property;
  gobject_class->set_property = dblcap_external_skeleton_set_property;
  gobject_class->notify       = dblcap_external_skeleton_notify;


  dblcap_external_override_properties (gobject_class, 1);

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = dblcap_external_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = dblcap_external_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = dblcap_external_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = dblcap_external_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (DBLCapExternalSkeletonPrivate));
#endif
}

static void
dblcap_external_skeleton_iface_init (DBLCapExternalIface *iface)
{
  iface->get_keep_above = dblcap_external_skeleton_get_keep_above;
}

/**
 * dblcap_external_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-net-sapples-LiveCaptions-External.top_of_page">net.sapples.LiveCaptions.External</link>.
 *
 * Returns: (transfer full) (type DBLCapExternalSkeleton): The skeleton object.
 */
DBLCapExternal *
dblcap_external_skeleton_new (void)
{
  return DBLCAP_EXTERNAL (g_object_new (DBLCAP_TYPE_EXTERNAL_SKELETON, NULL));
}

/* ------------------------------------------------------------------------
 * Code for Object, ObjectProxy and ObjectSkeleton
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:DBLCapObject
 * @title: DBLCapObject
 * @short_description: Specialized GDBusObject types
 *
 * This section contains the #DBLCapObject, #DBLCapObjectProxy, and #DBLCapObjectSkeleton types which make it easier to work with objects implementing generated types for D-Bus interfaces.
 */

/**
 * DBLCapObject:
 *
 * The #DBLCapObject type is a specialized container of interfaces.
 */

/**
 * DBLCapObjectIface:
 * @parent_iface: The parent interface.
 *
 * Virtual table for the #DBLCapObject interface.
 */

typedef DBLCapObjectIface DBLCapObjectInterface;
G_DEFINE_INTERFACE_WITH_CODE (DBLCapObject, dblcap_object, G_TYPE_OBJECT, g_type_interface_add_prerequisite (g_define_type_id, G_TYPE_DBUS_OBJECT);)

static void
dblcap_object_default_init (DBLCapObjectIface *iface)
{
  /**
   * DBLCapObject:external:
   *
   * The #DBLCapExternal instance corresponding to the D-Bus interface <link linkend="gdbus-interface-net-sapples-LiveCaptions-External.top_of_page">net.sapples.LiveCaptions.External</link>, if any.
   *
   * Connect to the #GObject::notify signal to get informed of property changes.
   */
  g_object_interface_install_property (iface, g_param_spec_object ("external", "external", "external", DBLCAP_TYPE_EXTERNAL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));

}

/**
 * dblcap_object_get_external:
 * @object: A #DBLCapObject.
 *
 * Gets the #DBLCapExternal instance for the D-Bus interface <link linkend="gdbus-interface-net-sapples-LiveCaptions-External.top_of_page">net.sapples.LiveCaptions.External</link> on @object, if any.
 *
 * Returns: (transfer full) (nullable): A #DBLCapExternal that must be freed with g_object_unref() or %NULL if @object does not implement the interface.
 */
DBLCapExternal *dblcap_object_get_external (DBLCapObject *object)
{
  GDBusInterface *ret;
  ret = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "net.sapples.LiveCaptions.External");
  if (ret == NULL)
    return NULL;
  return DBLCAP_EXTERNAL (ret);
}


/**
 * dblcap_object_peek_external: (skip)
 * @object: A #DBLCapObject.
 *
 * Like dblcap_object_get_external() but doesn't increase the reference count on the returned object.
 *
 * It is not safe to use the returned object if you are on another thread than the one where the #GDBusObjectManagerClient or #GDBusObjectManagerServer for @object is running.
 *
 * Returns: (transfer none) (nullable): A #DBLCapExternal or %NULL if @object does not implement the interface. Do not free the returned object, it is owned by @object.
 */
DBLCapExternal *dblcap_object_peek_external (DBLCapObject *object)
{
  GDBusInterface *ret;
  ret = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "net.sapples.LiveCaptions.External");
  if (ret == NULL)
    return NULL;
  g_object_unref (ret);
  return DBLCAP_EXTERNAL (ret);
}


static void
dblcap_object_notify (GDBusObject *object, GDBusInterface *interface)
{
  _ExtendedGDBusInterfaceInfo *info = (_ExtendedGDBusInterfaceInfo *) g_dbus_interface_get_info (interface);
  /* info can be NULL if the other end is using a D-Bus interface we don't know
   * anything about, for example old generated code in this process talking to
   * newer generated code in the other process. */
  if (info != NULL)
    g_object_notify (G_OBJECT (object), info->hyphen_name);
}

/**
 * DBLCapObjectProxy:
 *
 * The #DBLCapObjectProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * DBLCapObjectProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #DBLCapObjectProxy.
 */

static void
dblcap_object_proxy__dblcap_object_iface_init (DBLCapObjectIface *iface G_GNUC_UNUSED)
{
}

static void
dblcap_object_proxy__g_dbus_object_iface_init (GDBusObjectIface *iface)
{
  iface->interface_added = dblcap_object_notify;
  iface->interface_removed = dblcap_object_notify;
}


G_DEFINE_TYPE_WITH_CODE (DBLCapObjectProxy, dblcap_object_proxy, G_TYPE_DBUS_OBJECT_PROXY,
                         G_IMPLEMENT_INTERFACE (DBLCAP_TYPE_OBJECT, dblcap_object_proxy__dblcap_object_iface_init)
                         G_IMPLEMENT_INTERFACE (G_TYPE_DBUS_OBJECT, dblcap_object_proxy__g_dbus_object_iface_init))

static void
dblcap_object_proxy_init (DBLCapObjectProxy *object G_GNUC_UNUSED)
{
}

static void
dblcap_object_proxy_set_property (GObject      *gobject,
  guint         prop_id,
  const GValue *value G_GNUC_UNUSED,
  GParamSpec   *pspec)
{
  G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
}

static void
dblcap_object_proxy_get_property (GObject      *gobject,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
  DBLCapObjectProxy *object = DBLCAP_OBJECT_PROXY (gobject);
  GDBusInterface *interface;

  switch (prop_id)
    {
    case 1:
      interface = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "net.sapples.LiveCaptions.External");
      g_value_take_object (value, interface);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
      break;
  }
}

static void
dblcap_object_proxy_class_init (DBLCapObjectProxyClass *klass)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (klass);

  gobject_class->set_property = dblcap_object_proxy_set_property;
  gobject_class->get_property = dblcap_object_proxy_get_property;

  g_object_class_override_property (gobject_class, 1, "external");
}

/**
 * dblcap_object_proxy_new:
 * @connection: A #GDBusConnection.
 * @object_path: An object path.
 *
 * Creates a new proxy object.
 *
 * Returns: (transfer full): The proxy object.
 */
DBLCapObjectProxy *
dblcap_object_proxy_new (GDBusConnection *connection,
  const gchar *object_path)
{
  g_return_val_if_fail (G_IS_DBUS_CONNECTION (connection), NULL);
  g_return_val_if_fail (g_variant_is_object_path (object_path), NULL);
  return DBLCAP_OBJECT_PROXY (g_object_new (DBLCAP_TYPE_OBJECT_PROXY, "g-connection", connection, "g-object-path", object_path, NULL));
}

/**
 * DBLCapObjectSkeleton:
 *
 * The #DBLCapObjectSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * DBLCapObjectSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #DBLCapObjectSkeleton.
 */

static void
dblcap_object_skeleton__dblcap_object_iface_init (DBLCapObjectIface *iface G_GNUC_UNUSED)
{
}


static void
dblcap_object_skeleton__g_dbus_object_iface_init (GDBusObjectIface *iface)
{
  iface->interface_added = dblcap_object_notify;
  iface->interface_removed = dblcap_object_notify;
}

G_DEFINE_TYPE_WITH_CODE (DBLCapObjectSkeleton, dblcap_object_skeleton, G_TYPE_DBUS_OBJECT_SKELETON,
                         G_IMPLEMENT_INTERFACE (DBLCAP_TYPE_OBJECT, dblcap_object_skeleton__dblcap_object_iface_init)
                         G_IMPLEMENT_INTERFACE (G_TYPE_DBUS_OBJECT, dblcap_object_skeleton__g_dbus_object_iface_init))

static void
dblcap_object_skeleton_init (DBLCapObjectSkeleton *object G_GNUC_UNUSED)
{
}

static void
dblcap_object_skeleton_set_property (GObject      *gobject,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  DBLCapObjectSkeleton *object = DBLCAP_OBJECT_SKELETON (gobject);
  GDBusInterfaceSkeleton *interface;

  switch (prop_id)
    {
    case 1:
      interface = g_value_get_object (value);
      if (interface != NULL)
        {
          g_warn_if_fail (DBLCAP_IS_EXTERNAL (interface));
          g_dbus_object_skeleton_add_interface (G_DBUS_OBJECT_SKELETON (object), interface);
        }
      else
        {
          g_dbus_object_skeleton_remove_interface_by_name (G_DBUS_OBJECT_SKELETON (object), "net.sapples.LiveCaptions.External");
        }
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
      break;
  }
}

static void
dblcap_object_skeleton_get_property (GObject      *gobject,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
  DBLCapObjectSkeleton *object = DBLCAP_OBJECT_SKELETON (gobject);
  GDBusInterface *interface;

  switch (prop_id)
    {
    case 1:
      interface = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "net.sapples.LiveCaptions.External");
      g_value_take_object (value, interface);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
      break;
  }
}

static void
dblcap_object_skeleton_class_init (DBLCapObjectSkeletonClass *klass)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (klass);

  gobject_class->set_property = dblcap_object_skeleton_set_property;
  gobject_class->get_property = dblcap_object_skeleton_get_property;

  g_object_class_override_property (gobject_class, 1, "external");
}

/**
 * dblcap_object_skeleton_new:
 * @object_path: An object path.
 *
 * Creates a new skeleton object.
 *
 * Returns: (transfer full): The skeleton object.
 */
DBLCapObjectSkeleton *
dblcap_object_skeleton_new (const gchar *object_path)
{
  g_return_val_if_fail (g_variant_is_object_path (object_path), NULL);
  return DBLCAP_OBJECT_SKELETON (g_object_new (DBLCAP_TYPE_OBJECT_SKELETON, "g-object-path", object_path, NULL));
}

/**
 * dblcap_object_skeleton_set_external:
 * @object: A #DBLCapObjectSkeleton.
 * @interface_: (nullable): A #DBLCapExternal or %NULL to clear the interface.
 *
 * Sets the #DBLCapExternal instance for the D-Bus interface <link linkend="gdbus-interface-net-sapples-LiveCaptions-External.top_of_page">net.sapples.LiveCaptions.External</link> on @object.
 */
void dblcap_object_skeleton_set_external (DBLCapObjectSkeleton *object, DBLCapExternal *interface_)
{
  g_object_set (G_OBJECT (object), "external", interface_, NULL);
}


/* ------------------------------------------------------------------------
 * Code for ObjectManager client
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:DBLCapObjectManagerClient
 * @title: DBLCapObjectManagerClient
 * @short_description: Generated GDBusObjectManagerClient type
 *
 * This section contains a #GDBusObjectManagerClient that uses dblcap_object_manager_client_get_proxy_type() as the #GDBusProxyTypeFunc.
 */

/**
 * DBLCapObjectManagerClient:
 *
 * The #DBLCapObjectManagerClient structure contains only private data and should only be accessed using the provided API.
 */

/**
 * DBLCapObjectManagerClientClass:
 * @parent_class: The parent class.
 *
 * Class structure for #DBLCapObjectManagerClient.
 */

G_DEFINE_TYPE (DBLCapObjectManagerClient, dblcap_object_manager_client, G_TYPE_DBUS_OBJECT_MANAGER_CLIENT)

static void
dblcap_object_manager_client_init (DBLCapObjectManagerClient *manager G_GNUC_UNUSED)
{
}

static void
dblcap_object_manager_client_class_init (DBLCapObjectManagerClientClass *klass G_GNUC_UNUSED)
{
}

/**
 * dblcap_object_manager_client_get_proxy_type:
 * @manager: A #GDBusObjectManagerClient.
 * @object_path: The object path of the remote object (unused).
 * @interface_name: (nullable): Interface name of the remote object or %NULL to get the object proxy #GType.
 * @user_data: User data (unused).
 *
 * A #GDBusProxyTypeFunc that maps @interface_name to the generated #GDBusObjectProxy derived and #GDBusProxy derived types.
 *
 * Returns: A #GDBusProxy derived #GType if @interface_name is not %NULL, otherwise the #GType for #DBLCapObjectProxy.
 */
GType
dblcap_object_manager_client_get_proxy_type (GDBusObjectManagerClient *manager G_GNUC_UNUSED, const gchar *object_path G_GNUC_UNUSED, const gchar *interface_name, gpointer user_data G_GNUC_UNUSED)
{
  static gsize once_init_value = 0;
  static GHashTable *lookup_hash;
  GType ret;

  if (interface_name == NULL)
    return DBLCAP_TYPE_OBJECT_PROXY;
  if (g_once_init_enter (&once_init_value))
    {
      lookup_hash = g_hash_table_new (g_str_hash, g_str_equal);
      g_hash_table_insert (lookup_hash, (gpointer) "net.sapples.LiveCaptions.External", GSIZE_TO_POINTER (DBLCAP_TYPE_EXTERNAL_PROXY));
      g_once_init_leave (&once_init_value, 1);
    }
  ret = (GType) GPOINTER_TO_SIZE (g_hash_table_lookup (lookup_hash, interface_name));
  if (ret == (GType) 0)
    ret = G_TYPE_DBUS_PROXY;
  return ret;
}

/**
 * dblcap_object_manager_client_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates #GDBusObjectManagerClient using dblcap_object_manager_client_get_proxy_type() as the #GDBusProxyTypeFunc. See g_dbus_object_manager_client_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call dblcap_object_manager_client_new_finish() to get the result of the operation.
 *
 * See dblcap_object_manager_client_new_sync() for the synchronous, blocking version of this constructor.
 */
void
dblcap_object_manager_client_new (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data)
{
  g_async_initable_new_async (DBLCAP_TYPE_OBJECT_MANAGER_CLIENT, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "flags", flags, "name", name, "connection", connection, "object-path", object_path, "get-proxy-type-func", dblcap_object_manager_client_get_proxy_type, NULL);
}

/**
 * dblcap_object_manager_client_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to dblcap_object_manager_client_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with dblcap_object_manager_client_new().
 *
 * Returns: (transfer full) (type DBLCapObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
dblcap_object_manager_client_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}

/**
 * dblcap_object_manager_client_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates #GDBusObjectManagerClient using dblcap_object_manager_client_get_proxy_type() as the #GDBusProxyTypeFunc. See g_dbus_object_manager_client_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See dblcap_object_manager_client_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type DBLCapObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
dblcap_object_manager_client_new_sync (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error)
{
  GInitable *ret;
  ret = g_initable_new (DBLCAP_TYPE_OBJECT_MANAGER_CLIENT, cancellable, error, "flags", flags, "name", name, "connection", connection, "object-path", object_path, "get-proxy-type-func", dblcap_object_manager_client_get_proxy_type, NULL);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}


/**
 * dblcap_object_manager_client_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like dblcap_object_manager_client_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call dblcap_object_manager_client_new_for_bus_finish() to get the result of the operation.
 *
 * See dblcap_object_manager_client_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
dblcap_object_manager_client_new_for_bus (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data)
{
  g_async_initable_new_async (DBLCAP_TYPE_OBJECT_MANAGER_CLIENT, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "flags", flags, "name", name, "bus-type", bus_type, "object-path", object_path, "get-proxy-type-func", dblcap_object_manager_client_get_proxy_type, NULL);
}

/**
 * dblcap_object_manager_client_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to dblcap_object_manager_client_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with dblcap_object_manager_client_new_for_bus().
 *
 * Returns: (transfer full) (type DBLCapObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
dblcap_object_manager_client_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}

/**
 * dblcap_object_manager_client_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like dblcap_object_manager_client_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See dblcap_object_manager_client_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type DBLCapObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
dblcap_object_manager_client_new_for_bus_sync (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error)
{
  GInitable *ret;
  ret = g_initable_new (DBLCAP_TYPE_OBJECT_MANAGER_CLIENT, cancellable, error, "flags", flags, "name", name, "bus-type", bus_type, "object-path", object_path, "get-proxy-type-func", dblcap_object_manager_client_get_proxy_type, NULL);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}


