name: Flatpak

on: [push, pull_request]

jobs:
  x86_64:
    name: "x86_64"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: flatpak/flatpak-github-actions/flatpak-builder@master
      with:
        manifest-path: build-aux/flatpak/net.sapples.LiveCaptions.json
        cache-key: flatpak-builder-${{ github.sha }}
