name: ci_meson

on: [push, pull_request]

jobs:

  linux:
    runs-on: ubuntu-latest
    env:
      ONNX_ROOT: $GITHUB_WORKSPACE/onnxruntime-linux-x64-1.13.1/
      ONNXRuntime_INCLUDE_DIR: $GITHUB_WORKSPACE/onnxruntime-linux-x64-1.13.1/include
      ONNXRuntime_LIBRARY: $GITHUB_WORKSPACE/onnxruntime-linux-x64-1.13.1/lib
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$GITHUB_WORKSPACE/onnxruntime-linux-x64-1.13.1/lib
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install meson ninja
    - name: Download ONNX
      run: |
        wget https://github.com/microsoft/onnxruntime/releases/download/v1.13.1/onnxruntime-linux-x64-1.13.1.tgz
        tar -xf onnxruntime-linux-x64-1.13.1.tgz
    - run: meson setup builddir
      env:
        CC: gcc
    - run: meson devenv -C builddir
    - run: ninja
